### ISSUE TITLE
Сделать AppImage сборки для других Linux дистрибутивов

### ISSUE THREAD

**Issue by hitman249** [vodka2/vk-music-fs#1]
для этого понадобятся файлы:

1. **appimagetool-x86_64.AppImage**
2. **AppRun-x86_64** нужно переименовать в **AppRun**

https://github.com/AppImage/AppImageKit/releases

Здесь есть инструкция как сделать пакет, см. метод **generate_appdir()**

https://github.com/wxphp/appimage/blob/master/appimage.sh

В конце выполнить просто:
`./appimagetool-x86_64.AppImage ./vk-music-fs.AppDir`

**Comment by vodka2** [comment]
@hitman249 Хорошо, я попробую. Но пока что это не очень в приоритете, я собираюсь сначала выложить в AUR.

**Comment by hitman249** [comment]
Для ещё более быстрого погружения в тему)

Так выглядит папка **app.AppDir** внутри (`.DirIcon` создаётся автоматически)
Здесь самое главное, чтобы бинарник в `/usr/bin`, файл иконки, файл `*.desktop` и название внутри него имели одно и тоже имя

В остальном всё просто, копируешь все зависимости по аналогичным папкам из linux системы

![screenshot](https://user-images.githubusercontent.com/1325326/45604676-eec03200-ba60-11e8-8d6d-28fb9d356be0.png)

Тестировать лучше начиная с Debian 8, тогда точно запустится у всех

**Comment by vodka2** [comment]
@hitman249 ни разу не делал ещё AppImage, получилось как-то [так](https://github.com/vodka2/vk-music-fs/tree/appimage). Перед запуском скрипта нужно скомпилировать vk-music-fs и поместить исполняемые файлы в appimage/app-x86 и appimage/app-x86_64. Потом, наверно, я добавлю скомпилированные файлы в релиз и буду загружать их с Github. 
Вот сами AppImage: [imgs.zip](https://github.com/vodka2/vk-music-fs/files/2407931/imgs.zip)
