### ISSUE TITLE
fusermount: old style mounting not supported

### ISSUE THREAD

**Issue by algor512** [vodka2/vk-music-fs#6]
System:
Debian testing, vk-music-fs 1.3.1

When trying to run vk-music-fs I have
```
$ ./vk_music_fs-x86_64.AppImage ~/vk_music
fusermount: old style mounting not supported
```

**Comment by vodka2** [comment]
This is related to https://github.com/darealshinji/AppImageKit-checkrt/issues/17 . Just tried the code from that issue with [linuxdeploy-plugin-checkrt](https://github.com/linuxdeploy/linuxdeploy-plugin-checkrt), and the mounting is successful. I will update the build script.

There is an ugly workaround, that should work for now
```
./vk_music_fs-x86_64.AppImage --appimage-extract
./squashfs-root/AppRun  ~/vk_music
```

**Comment by vodka2** [comment]
@algor512 Appimages seem to be fixed now. Could you please try to run one of them from the latest [release](https://github.com/vodka2/vk-music-fs/releases/tag/1.3.2)?

**Comment by algor512** [comment]
I've just checked, it starts. But I have another problem: dirs are empty:
```
$ ls vk_music
'My audios'  'My playlists'   Search  'Search by artist'
$ cd vk_music/My\ audios/
$ ls
$ ps aux | grep vk_music
<...> ./vk_music_fs-x86_64.AppImage --log_err_to_file 1 /home/algor/vk_music
```

**Comment by vodka2** [comment]
They are empty by default, you have to create `1000` dir in My audios, for example, to load the first 1000 audios. This is described in README. 

Or, if you already created such dir and it does not work there should be some errors in the log. Could you post them?

**Comment by algor512** [comment]
> They are empty by default, you have to create 1000 dir in My audios, for example, to load the first 1000 audios. This is described in README.

Thank you, it works!
